"""Generate per-story Makefiles for pandoc builds."""

from __future__ import annotations

from pathlib import Path

from .options import StoryScraperOptions

MAKEFILE_TEMPLATE = """# Auto-generated by StoryScraper
TITLE := "{title}"
AUTHOR := "{author}"
TITLE_SLUG := "{slug}"

MARKDOWN_DIR := markdown
OUT_DIR := out
MD_FILES := $(sort $(wildcard $(MARKDOWN_DIR)/*.md))

HTML := $(OUT_DIR)/$(TITLE_SLUG).html
EPUB := $(OUT_DIR)/$(TITLE_SLUG).epub
ODT := $(OUT_DIR)/$(TITLE_SLUG).odt
DOCX := $(OUT_DIR)/$(TITLE_SLUG).docx

.PHONY: all clean date

all: $(HTML) $(EPUB) $(ODT) $(DOCX)

$(OUT_DIR):
\tmkdir -p $(OUT_DIR)

$(HTML): $(MD_FILES) | $(OUT_DIR)
\tpandoc $(MD_FILES) --metadata title=$(TITLE) --metadata author=$(AUTHOR) -o $@

$(EPUB): $(MD_FILES) | $(OUT_DIR)
\tpandoc $(MD_FILES) --toc --toc-depth=3 --metadata title=$(TITLE) --metadata author=$(AUTHOR) -o $@

$(ODT): $(MD_FILES) | $(OUT_DIR)
\tpandoc $(MD_FILES) --metadata title=$(TITLE) --metadata author=$(AUTHOR) -o $@

$(DOCX): $(MD_FILES) | $(OUT_DIR)
\tpandoc $(MD_FILES) --metadata title=$(TITLE) --metadata author=$(AUTHOR) -o $@

clean:
\trm -rf $(OUT_DIR)

date:
\t@echo "Date: $(shell date)"
"""


def write_makefile(
    options: StoryScraperOptions,
    *,
    stories_root: Path | None = None,
) -> Path:
    """Create/update the Makefile within the story directory."""

    root = Path(stories_root) if stories_root is not None else Path("stories")
    story_dir = root / options.effective_slug()
    story_dir.mkdir(parents=True, exist_ok=True)

    content = MAKEFILE_TEMPLATE.format(
        title=options.effective_name(),
        author=options.effective_author(),
        slug=options.effective_slug(),
    )

    makefile_path = story_dir / "Makefile"
    makefile_path.write_text(content, encoding="utf-8")
    return makefile_path
